### Petición GET
GET http://127.0.0.1:8000/api/prueba
Content-Type: application/json

### Send POST request with json body
POST http://127.0.0.1:8000//api/imagenesapinueva

Content-Type: application/json
{
"nombre": "imagen post 1",
"descripcion": "esta es la imagen post 1",
"numVisualizaciones": "21",
"numLikes": "12",
"numDownloads": "4",
"categoria": "2",
"usuario": "3",
"fecha": "20/01/2024"
}