### Petición GET
GET http://127.0.0.1:8000/api/prueba
Content-Type: application/json

### Send POST request with json body
POST http://127.0.0.1:8000/api/imagenesapinueva
Content-Type: application/json

{
"nombre": "imagen post 1",
"descripcion": "esta es la imagen post 1",
"numVisualizaciones": "21",
"numLikes": "12",
"numDownloads": "4",
"categoria": "1",
"usuario": "1",
"fecha": "20/01/2024"
}

### GET para obtener todos los datos ordenados
GET http://127.0.0.1:8000/api/imagenesapi/ordenadas/descripcion
Content-Type: application/json

### GET para obtener datos filtrados
GET http://127.0.0.1:8000/api/imagenesapi/ordenadas/id?fechaInicial=2024-01-03&descripcion=imag
Content-Type: application/json
